pages:
- Home: 'index.md'
- Objects:
  - Object types: 'object-types.md'
  - Object properties: 'object-properties.md'
  - Object revisions: 'object-revisions.md'
  - Object states: 'object-states.md'
  - Object URLs: 'object-url.md'
  - Object hash: 'object-hash.md'
- To-Do: 'object-todo.md'

