site_name: apparat/object
site_description: Apparat object abstraction layer
site_author: Joschi Kuphal
repo_url: https://github.com/apparat/object/
docs_dir: doc
pages:
- Home: 'index.md'
- Objects:
  - Types: 'object-types.md'
  - Properties: 'object-properties.md'
  - Identifiers, URLs & selectors: 'object-identifier.md'
  - Revisions: 'object-revisions.md'
  - States: 'object-states.md'
- To-Do: 'todo.md'
