site_name: apparat/object
site_description: Apparat object abstraction layer
site_author: Joschi Kuphal
repo_url: https://github.com/apparat/object/
docs_dir: doc
pages:
- Home: 'index.md'
- Objects:
  - Object types: 'object-types.md'
  - Object properties: 'object-properties.md'
  - Object revisions: 'object-revisions.md'
  - Object states: 'object-states.md'
  - Object URLs: 'object-url.md'
  - Object hash: 'object-hash.md'
- To-Do: 'object-todo.md'
